### PR TITLE
adding OpenConfig() and doing some cleanup

### PR DESCRIPTION
**Pull request by mshafer1**
* added OpenConfig as an option
* Changed from using multi-line strings to using string templates
* Changed from testing with Internet Explorer to Edge (supports templates)

### CODE REVIEW

**Comment by mshafer1** [comment]
I think this will resolve the issue of using characters for the hotkey (tested).

**Comment by mshafer1** [comment]
Regarding file: vs http: - I am using the page URL that is the generator, but chrome and others will block URLs (file:) like that from opening. I suspect that is the issue.

**Comment by ptar** [comment]
For the percent sign, you just used the wrong escape character. It must be '`' instead of '^'.
I pushed the change in keygen.js

**Comment by ptar** [comment]
file vs. http: It works for me with the manual change to ahkgen.com
So I approve the change.

**Pull request merged**
